modLoader = "${mod_loader}"
loaderVersion = "${mod_loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/dsx137/lavafishing"
logoFile = "logo.png"
authors = "${mod_authors}"
credits = "${mod_credits}"

description = '''${mod_description}'''

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "aquaculture"
mandatory = true
versionRange = "${aquaculture_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "kotlinforforge"
mandatory = false # kff template replace
versionRange = "${kotlin_for_forge_version_range}"
ordering = "NONE"
side = "BOTH"